app/Http/routes.php
<?php

Route::get('/test', function () {

    // echo "<pre>";
    // print_r(App\Category::select(['id', 'name'])->get()->toArray());

     Artisan::call('crawler:zing');

    // $news = App\News::all();
    // foreach ($news as $n)
    // {
    //     print_r($n->category);
    // }

    // $cate = App\Category::find(1);
    // dd($cate->news);


});

// Frontend
Route::group(['middleware' => ['web']], function () {

    Route::get('/', ['as' => 'home', 'uses' => 'FrontEndController@home']);
    Route::get('/about', ['as' => 'about', 'uses' => 'FrontEndController@about']);
    Route::get('/contact', ['as' => 'contact', 'uses' => 'FrontEndController@contact']);


    Route::get('/danh-muc/{slug}', ['as' => 'trang_danh_muc', 'uses' => 'FrontEndController@trang_tin_tuc_theo_danh_muc']);
    Route::get('/tin-tuc/{slug}', ['as' => 'trang_chi_tiet_tin_tuc', 'uses' => 'FrontEndController@trang_chi_tiet_tin_tuc']);

});


// dang nhap, dang xuat, dang ky
Route::group(['middleware' => ['web']], function () {
    Route::get('/login', ['as' => 'login', 'uses' => 'Auth\AuthController@getLogin']);
    Route::post('/login', ['as' => 'postLogin', 'uses' => 'Auth\AuthController@postLogin']);
    Route::get('/register', ['as' => 'register', 'uses' => 'Auth\AuthController@getRegister']);
    Route::post('/register', ['as' => 'postRegister', 'uses' => 'Auth\AuthController@postRegister']);
    Route::get('/logout', ['as' => 'logout', 'uses' => 'Auth\AuthController@logout']);
});


// Backend nhóm xử lý hệ thống
Route::group(['middleware' => ['web', 'auth']], function () {

    Route::group(['prefix' => 'backend'], function () {
        Route::get('/', function () {
            return redirect()->route('dashboard');
        });

        Route::get('/dashboard', ['as' => 'dashboard', function () {
            return view('backend.page.dashboard');
        }]);

        Route::resource('category', 'CategoryController');
        Route::resource('news', 'NewsController');
        Route::resource('comment', 'CommentController');
    });
});

app/News.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use Carbon\Carbon;

class News extends Model
{
    protected $fillable = ['title', 'image', 'slug', 'category_id', 'description', 'content', 'publish_at', 'user_id'];

    public function category()
    {
    	return $this->belongsTo('App\Category', 'category_id', 'id');
    }

    public function user()
    {
    	return $this->belongsTo('App\User', 'user_id', 'id');
    }

    public function comments()
    {
        return $this->hasMany('App\Comment', 'news_id', 'id');
    }

    public function publist_at_human()
    {
    	return Carbon::createFromFormat('Y-m-d H:i:s', $this->publish_at)->diffForHumans();
    }
}

app/Http/Controllers/NewsController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use Illuminate\Support\Str;

use App\Http\Requests;
use App\Http\Controllers\Controller;

use App\News;

class NewsController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $list_news = News::paginate(20);
        return view('backend.news.index')
            ->with('list_news', $list_news);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('backend.news.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $input = $request->only([
                'title', 
                'category_id', 
                'description', 
                'content', 
                'publish_at'
            ]);
        $input['slug'] = Str::slug($input['title']);

        News::create($input);
        return redirect()->back()->withSuccess('Thêm tin tức thành công');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        return view('backend.news.edit')
            ->withNews(News::find($id));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $input = $request->only([
            'title', 
            'category_id', 
            'description', 
            'content', 
            'publish_at'
        ]);
        $input['slug'] = Str::slug($input['title']);

        $news = News::find($id);
        $news->update($input);

        return redirect()->back()
            ->withSuccess('Sửa thành công');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        News::destroy($id);
        return redirect()->back()
            ->withSuccess("Xóa thành công");
    }
}

resources/views/backend/news/create.blade.php
@extends('backend.layout.layout')
@section('title', 'Create News')
@section('content')
	<div class="page-header">
		<h1>Create News</h1>	
	</div>

	<div class="row">
		<div class="col-sm-8">
			@include('backend.common.alert')
			@include('backend.common.error')
		</div>
	</div>

	<hr>


	<div class="row">
		<div class="col-sm-8">
			<p>
				<a href="{{route('backend.news.index')}}" class="pull-right"><i class="icon-arrow-left"></i>List News</a>
			</p>
			<form action="{{route('backend.news.store')}}" method="POST" role="form">
				{{csrf_field()}}
				{{method_field('POST')}}
				<div class="form-group">
					<label for="title">Title</label>
					<input type="text" name="title" id="inputTitle" class="form-control" value="" title="">
				</div>
				
				<div class="form-group">
					<label for="category_id">Category</label>
					<select name="category_id" id="inputCategory_id" class="form-control">
						<option value="0">-- Select One --</option>
						@foreach (App\Category::all() as $cate)
							<option value="{{$cate->id}}">{{$cate->name}}</option>
						@endforeach
					</select>
				</div>

				<div class="form-group">
					<label for="slug">Slug</label>
					<input type="text" name="slug" id="inputSlug" class="form-control" value="" title="" disabled>
				</div>
				<div class="form-group">
					<label for="description">Description</label>
					<textarea name="description" id="inputDescription" class="form-control" rows="3"></textarea>
				</div>
				<div class="form-group">
					<label for="content">Content</label>
					<textarea name="content" id="inputContent" class="form-control" rows="50"></textarea>
				</div>
				<div class="form-group">
					<label for="publish_at">Publish at</label>
					<input type="date" name="publish_at" id="inputPublish_at" class="form-control" value="" title="">
				</div>

				<button type="submit" class="btn btn-success"><i class="icon-plus"></i> Add news</button>

			</form>
		</div>
	</div>
	
		
@stop

@section('js')
	@parent
	@include('backend.common.editor')
@stop

resources/views/backend/news/edit.blade.php
@extends('backend.layout.layout')
@section('title', 'Edit News # '.$news->id)
@section('content')
	<div class="page-header">
		<h1>Edit News # {{$news->id}}</h1>	
	</div>

	<div class="row">
		<div class="col-sm-8">
			@include('backend.common.alert')
			@include('backend.common.error')
		</div>
	</div>

	<hr>


	<div class="row">
		<div class="col-sm-8">
			<p>
				<a href="{{route('backend.news.index')}}" class="pull-right"><i class="icon-arrow-left"></i>List News</a>
			</p>
			<form action="{{route('backend.news.update', ['id' => $news->id])}}" method="POST" role="form">
				{{csrf_field()}}
				{{method_field('PUT')}}
				<div class="form-group">
					<label for="title">Title</label>
					<input type="text" name="title" id="inputTitle" class="form-control" value="{{$news->title}}" title="">
				</div>

				<div class="row">

					<div class="col-sm-6">
						<div class="form-group">
							<label for="category_id">Category</label>
							<select name="category_id" id="inputCategory_id" class="form-control">
								<option value="0">-- Select One --</option>
								@foreach (App\Category::all() as $cate)
									@if ($cate->id == $news->category_id)
										<option value="{{$cate->id}}" selected>{{$cate->name}} --- đang chọn</option>
									@endif
									<option value="{{$cate->id}}">{{$cate->name}}</option>
								@endforeach
							</select>
						</div>

						<div class="form-group">
							<label for="slug">Slug</label>
							<input type="text" name="slug" id="inputSlug" class="form-control" value="{{$news->slug}}" title="" disabled>
						</div>


					</div>

					<div class="col-sm-6">
						@if ($news->image)
							<a href="#" class="thumbnail">
								<img src="{{url($news->image)}}" alt="{{$news->title}}" >
							</a>
						@else
							<span class="label label-warning">No image</span>
						@endif
					</div>
				</div>

				<div class="form-group">
					<label for="inputImage">Image</label>
					<input type="text" name="image" id="inputImage" class="form-control" value="{{$news->image}}" title="">
				</div>

				<div class="form-group">
					<label for="description">Description</label>
					<textarea name="description" id="inputDescription" class="form-control" rows="3">{{$news->description}}</textarea>
				</div>
				<div class="form-group">
					<label for="content">Content</label>
					<textarea name="content" id="inputContent" class="form-control" rows="50">{{$news->content}}</textarea>
				</div>
				<div class="form-group">
					<label for="publish_at">Publish at</label>
					{{-- <input type="text" name="publish_at" id="inputPublish_at" class="form_datetime form-control" value="{{$news->publish_at}}" title=""> --}}
					<div class="row">
						<div class="col-sm-4">
							<div class="input-group date form_datetime-component">
								<input type="text" name="publish_at" class="form-control" value="{{$news->publish_at}}">
								<span class="input-group-btn">
									<button type="button" class="btn btn-danger date-set"><i class="icon-calendar"></i></button>
								</span>
							</div>
						</div>
					</div>

				</div>

				<div class="form-group">
					<label for="created_at">Created at</label>
					<input type="datetime" name="created_at" id="inputcreated_at" class="form-control" value="{{$news->created_at}}" title="" disabled>
				</div>
				<div class="form-group">
					<label for="updated_at">Publish at</label>
					<input type="datetime" name="updated_at" id="inputupdated_at" class="form-control" value="{{$news->updated_at}}" title="" disabled>
				</div>

				<button type="submit" class="btn btn-success"><i class="icon-save"></i> Save</button>

			</form>
		</div>
	</div>


@stop

@section('css-append')
	@parent
	<link rel="stylesheet" href="{{url('assets/bootstrap-datetimepicker/css/datetimepicker.css')}}">
@stop

@section('js-append')
	@parent
	@include('backend.common.editor')
	<script type="text/javascript" src="{{url('assets/bootstrap-datetimepicker/js/bootstrap-datetimepicker.js')}}"></script>
	<script>
		$(document).ready(function() {
		    CKFinder.setupCKEditor();
		    CKEDITOR.replace( 'inputContent', {
		        filebrowserBrowseUrl: base_url+'/assets/ckfinder/ckfinder.html',
		        filebrowserUploadUrl: base_url+'/assets/ckfinder/core/connector/php/connector.php?command=QuickUpload&type=Files'
		    });
		    CKEDITOR.replace( 'inputContent' );

			$(".form_datetime").datetimepicker({format: 'yyyy-mm-dd hh:ii:ss'});
			$(".form_datetime-component").datetimepicker({format: 'yyyy-mm-dd hh:ii:ss'});
		});
	</script>
@stop

resources/views/backend/news/index.blade.php
@extends('backend.layout.layout')
@section('title', 'List News')
@section('css-append')
	@parent
	<link rel="stylesheet" href="{{url('assets/advanced-datatable/media/css/demo_table.css')}}">
	<style>
		table img {
			width: 100px;
		}
	</style>
@stop
@section('js-append')
	@parent
	<script src="{{url('assets/advanced-datatable/media/js/jquery.dataTables.js')}}"></script>
@stop
@section('content')
	<div class="page-header">
		<h1>List News</h1>	
	</div>

	<div class="row">
		<div class="col-sm-8">
			@include('backend.common.alert')
			@include('backend.common.error')
		</div>
	</div>

	<div class="row">
		<div class="col-sm-4">
			<a href="{{route('backend.news.create')}}"class="btn btn-primary ">
				<i class="icon-plus"></i> Add new
			</a>	
		</div>
	</div>
	
	<hr>

	<div class="row">
		<div class="col-sm-12">
		<div class="table-responsive">
			<table class="table table-hover table-striped">
				<thead>
					<tr>
						<th>id</th>
						<th>Hình ảnh</th>
						<th>Tiêu đề</th>
						<th>Danh mục</th>
						<th>Người đăng</th>
						<th>Xuất bản lúc</th>
						<th></th>
					</tr>
				</thead>
				<tbody>
				@foreach($list_news as $news)
					<tr>
						<td>{{$news->id}}</td>
						<td>
							@if ($news->image)
								<img src="{{url($news->image)}}" alt="{{$news->title}}" class="img-responsive" >
							@else
								<span class="label label-warning">No image</span>
							@endif
						</td>
						<td>{{$news->title}}</td>
						<td>
							{{$news->category->name or 'N/A'}}
						</td>
						<td>{{$news->user->name or 'N/A'}}</td>
						<td>{{$news->publish_at}}</td>
						<td>
						<a href="{{route('backend.news.edit', ['id'=> $news->id])}}" class="btn btn-primary btn-xs" alt="Edit"><i class="icon-pencil"></i></a>
						<form action="{{route('backend.news.destroy', ['id'=> $news->id])}}" method="post" class="form-inline" role="form">
							{{csrf_field()}}
							{{method_field('DELETE')}}
							<button type="submit" class="btn btn-danger btn-xs" alt="Edit"><i class="icon-trash "></i></button>
						</form>
					</td>
					</tr>
				@endforeach
				</tbody>
			</table>
		</div>
		{!! $list_news->links() !!}
		</div>
	</div>

@stop